name: Dependent Jobs with Alerts

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo "This is Job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1  # Make job2 dependent on job1
    steps:
      - name: Job 2
        run: echo "This is Job 2"

  job3:
    runs-on: ubuntu-latest
    needs: job2  # Make job3 dependent on job2
    steps:
      - name: Job 3
        run: echo "This is Job 3"
  
  alert:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]  # Make the alert job dependent on all previous jobs
    if: ${{ failure() }}  # Only run the alert job if any of the previous jobs fail
    steps:
      - name: Send Alert
        run: echo "One or more jobs failed, sending alert!"
